create index IDX_DF_ACCOUNT_DOC_ORIGDOC_ID on DF_ACCOUNT_DOC (ORIGIN_DOC_ID)^

create index IDX_DF_ACCOUNT_DOC_ORIGRDOC_ID on DF_ACCOUNT_DOC (ORIGIN_REV_DOC_ID)^

create index IDX_DF_ACCOUNT_DOC_ORIGCDOC_ID on DF_ACCOUNT_DOC (ORIGIN_COR_DOC_ID)^