-- $Id$


if exists (select NAME from SYSINDEXES where NAME = 'IDX_BASE_ACL_ID') drop index TS_CARD_ACL.IDX_BASE_ACL_ID^
create index IDX_BASE_ACL_ID on TS_CARD_ACL(BASE_ACL_ID)^
if exists (select NAME from SYSINDEXES where NAME = 'IDX_PARTICIPANT_ITEM') drop index TS_CALENDAR_EVENT_PARTICIPANT.IDX_PARTICIPANT_ITEM^
create index IDX_PARTICIPANT_ITEM on TS_CALENDAR_EVENT_PARTICIPANT (CALENDAR_EVENT_ITEM_ID)^
if exists (select NAME from SYSINDEXES where NAME = 'FK_TS_PUSH_NOT_CARD_INFO') drop index TS_PUSH_NOTIFICATION.FK_TS_PUSH_NOT_CARD_INFO^
create index FK_TS_PUSH_NOT_CARD_INFO ON TS_PUSH_NOTIFICATION(CARD_INFO_ID)^