create index IDX_USER_GROUP_ORG_ID on WF_USER_GROUP(ORGANIZATION_ID)^
create index IDX_U_GROUP_SUB_CREATOR_ID on WF_USER_GROUP(SUBSTITUTED_CREATOR_ID)^
create index IDX_WF_USER_GROUP_USER on WF_USER_GROUP_USER(USER_ID, USER_GROUP_ID)^