--$Id$
--Description:

drop index DF_APP_INTEGRATION_LOG.IDX_DF_ACCOUNTING_APP_INTEGRATION_LOG_CHANGES_SET_ID_INTEGRATION_STATE;


alter table DF_APP_INTEGRATION_LOG alter column CHANGES_SET_ID varchar(100);


create index IDX_DF_ACCOUNTING_APP_INTEGRATION_LOG_CHANGES_SET_ID_INTEGRATION_STATE on DF_APP_INTEGRATION_LOG (CHANGES_SET_ID, INTEGRATION_STATE)^

