--$Id$
alter table WF_ASSIGNMENT add BY_MAIL_CLIENT boolean^
alter table WF_ASSIGNMENT add SUBSTITUTED_CREATOR_ID uuid^

alter table WF_ASSIGNMENT add constraint FK_WF_ASSIGNMENT_SUBSTITUTED_CREATOR_ID foreign key (SUBSTITUTED_CREATOR_ID) references SEC_USER(ID)^

create index IDX_WF_ASSIGNMENT_SUBSTITUTED_CREATOR_ID on WF_ASSIGNMENT(SUBSTITUTED_CREATOR_ID)^