--$Id$
--$Description:

create table DF_OFFICE_FILE_OFFICE_FILE_NOMENCLATURE (
    DF_OFFICE_FILE_ID uuid,
    DF_OFFICE_FILE_NOMENCLATURE_ID uuid
)^

alter table DF_OFFICE_FILE_OFFICE_FILE_NOMENCLATURE add constraint DF_OFFICE_FILE_OFFICE_FILE_NOMENCLATURE_OFFICE_FILE foreign key (DF_OFFICE_FILE_ID) references DF_OFFICE_FILE(ID)^
alter table DF_OFFICE_FILE_OFFICE_FILE_NOMENCLATURE add constraint DF_OFFICE_FILE_OFFICE_FILE_NOMENCLATURE_NOMENCLATURE foreign key (DF_OFFICE_FILE_NOMENCLATURE_ID) references DF_OFFICE_FILE_NOMENCLATURE(ID)^
